region_name_mapper = {
    "Cherkasy": "Cherkasy",
    "Chernihiv": "Chernihiv",
    "Chernivtsi": "Chernivtsi",
    "Crimea": "Crimea",
    "Dnipropetrovs'k": "Dnipropetrovsk",
    "Donets'k": "Donetsk",
    "Ivano-Frankivs'k": "Ivano-Frankivsk",
    "Kharkiv": "Kharkiv",
    "Kherson": "Kherson",
    "Khmel'nyts'kyy": "Khmelnytskyi",
    "Kiev": "Kyiv",
    "Kiev City": "Kyiv City",
    "Kirovohrad": "Kirovohrad",
    "Luhans'k": "Luhansk",
    "L'viv": "Lviv",
    "Mykolayiv": "Mykolaiv",
    "Odessa": "Odesa",
    "Poltava": "Poltava",
    "Rivne": "Rivne",
    "Sevastopol'": "Sevastopol",
    "Sumy": "Sumy",
    "Ternopil'": "Ternopil",
    "Transcarpathia": "Transcarpathia",
    "Vinnytsya": "Vinnytsya",
    "Volyn": "Volyn",
    "Zaporizhzhya": "Zaporizhia",
    "Zhytomyr": "Zhytomyr",
    "Black Sea": "Black Sea"
}